// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6AusAH_s6xfTlESNI39VU2z1Jh-vLVcQ',
    appId: '1:973933568998:web:8b4e97534e11f386806c27',
    messagingSenderId: '973933568998',
    projectId: 'gemoy-kitchen-2026',
    authDomain: 'gemoy-kitchen-2026.firebaseapp.com',
    storageBucket: 'gemoy-kitchen-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPFwhDTriSayNLxaeUwBVbxPnC84MnInY',
    appId: '1:973933568998:ios:c65f4846f645c0f3806c27',
    messagingSenderId: '973933568998',
    projectId: 'gemoy-kitchen-2026',
    storageBucket: 'gemoy-kitchen-2026.firebasestorage.app',
    iosBundleId: 'com.gemoykitchen.gemoyKitchen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPFwhDTriSayNLxaeUwBVbxPnC84MnInY',
    appId: '1:973933568998:ios:c65f4846f645c0f3806c27',
    messagingSenderId: '973933568998',
    projectId: 'gemoy-kitchen-2026',
    storageBucket: 'gemoy-kitchen-2026.firebasestorage.app',
    iosBundleId: 'com.gemoykitchen.gemoyKitchen',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6AusAH_s6xfTlESNI39VU2z1Jh-vLVcQ',
    appId: '1:973933568998:web:b5934c5ca31a4345806c27',
    messagingSenderId: '973933568998',
    projectId: 'gemoy-kitchen-2026',
    authDomain: 'gemoy-kitchen-2026.firebaseapp.com',
    storageBucket: 'gemoy-kitchen-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq0U4Ek7_jCGmlFSSjX8HB7ixUERkp6UY',
    appId: '1:973933568998:android:2104a25379d7c53b806c27',
    messagingSenderId: '973933568998',
    projectId: 'gemoy-kitchen-2026',
    storageBucket: 'gemoy-kitchen-2026.firebasestorage.app',
  );

}